/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import Controller.AsistenciasLog.ReporteController;
import Controller.User.Sesion;
import Helpers.Navigation;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.sql.ResultSet;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;

public class FrmAtrasos extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmAtrasos.class.getName());

    ReporteController reporteCtrl = new ReporteController();
    //crea un objeto de sesion para poder traer datos del usuario actual
    //en este caso el tipo de usuario
    //IMPORTANTE!!! la IA te dira que esto esta mal y no se ejecutara por que esta fuera del constructor
    //pero se equivoca ademas funciona forma global en el codigo, si llamas al objsesion en cualquier parte puedes traer datos
    Sesion ObjSesion = new Sesion();
    String tipoUsuario = ObjSesion.getTipoUsuario();
    public FrmAtrasos() {
        this.setUndecorated(true);
        initComponents();
        Image icon = new ImageIcon(getClass().getResource("/Assets/TaskBarIcon.png")).getImage();
        setIconImage(icon);
        try {
            java.awt.Taskbar.getTaskbar().setIconImage(icon);
        } catch (Exception e) {
        }
        setSize(565, 461);
        setLocationRelativeTo(null);
        setResizable(false);

        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"), "salir");
        getRootPane().getActionMap().put("salir", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Navigation.Volver(FrmAtrasos.this, new FrmPrincipal(tipoUsuario));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        BtnVerAtrasos = new javax.swing.JButton();
        BtnVerSalidas = new javax.swing.JButton();
        BtnVerInasistencias = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Atrasos y faltas ");

        BtnVerAtrasos.setText("Atrasos");
        BtnVerAtrasos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerAtrasosActionPerformed(evt);
            }
        });

        BtnVerSalidas.setText("Salidas");
        BtnVerSalidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerSalidasActionPerformed(evt);
            }
        });

        BtnVerInasistencias.setText("Inasistencias");
        BtnVerInasistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerInasistenciasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(BtnVerAtrasos)
                .addGap(94, 94, 94)
                .addComponent(BtnVerSalidas)
                .addGap(74, 74, 74)
                .addComponent(BtnVerInasistencias))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnVerAtrasos)
                    .addComponent(BtnVerSalidas)
                    .addComponent(BtnVerInasistencias)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVerAtrasosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerAtrasosActionPerformed
        try {
            ResultSet rs = reporteCtrl.obtenerAtrasos();
            String[] columnas = {"Rut", "Nombre", "Fecha", "Hora Entrada"};
            DefaultTableModel modelo = new DefaultTableModel(null, columnas);

            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getString("Rut"),
                    rs.getString("NombreCompleto"),
                    rs.getDate("fecha"),
                    rs.getTime("hora")
                });
            }
            jTable1.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnVerAtrasosActionPerformed

    private void BtnVerSalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerSalidasActionPerformed
        try {
            ResultSet rs = reporteCtrl.obtenerSalidasAnticipadas();
            String[] columnas = {"Rut", "Nombre", "Fecha", "Hora Salida"};
            DefaultTableModel modelo = new DefaultTableModel(null, columnas);

            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getString("Rut"),
                    rs.getString("NombreCompleto"),
                    rs.getDate("fecha"),
                    rs.getTime("hora")
                });
            }
            jTable1.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnVerSalidasActionPerformed

    private void BtnVerInasistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerInasistenciasActionPerformed
         try {
            ResultSet rs = reporteCtrl.obtenerInasistencias();
            String[] columnas = {"Rut", "Nombre", "Fecha"};
            DefaultTableModel modelo = new DefaultTableModel(null, columnas);

            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getString("Rut"),
                    rs.getString("NombreCompleto"),
                    rs.getDate("fecha")
                });
            }
            jTable1.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_BtnVerInasistenciasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmAtrasos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVerAtrasos;
    private javax.swing.JButton BtnVerInasistencias;
    private javax.swing.JButton BtnVerSalidas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
