/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import Controller.User.Sesion;
import Helpers.Navigation;
import java.awt.CardLayout;
import Helpers.HoraDocumentFilter;
import javax.swing.text.AbstractDocument;
import Controller.Horario.HorarioController;
import java.awt.Image;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author jose9
 */
public class FrmConfiguracion extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmConfiguracion.class.getName());

    /**
     * Creates new form FrmConfiguracion
     */
    private CardLayout cardLayout;
    private HorarioController horarioController;
    Sesion ObjSesion = new Sesion();
    String tipoUsuario = ObjSesion.getTipoUsuario();

    public FrmConfiguracion(String tipoUsuario) {
        this.setUndecorated(true);
        initComponents();
        Image icon = new ImageIcon(getClass().getResource("/Assets/TaskBarIcon.png")).getImage();
        setLocationRelativeTo(null);
        setIconImage(icon);
      
        setLocationRelativeTo(null);
        Navigation.ControlAcceso(tipoUsuario, FrmConfiguracion.this, new FrmPrincipal(tipoUsuario));
        setSize(720, 480);
        setPreferredSize(new java.awt.Dimension(480, 720));
        cardLayout = new CardLayout();
        PnoContenido.setLayout(cardLayout);

        PnoContenido.add(PnoXd, "horario");
        PnoContenido.add(PnoHorario, "sonido");

        ((AbstractDocument) FTxtEntrada.getDocument()).setDocumentFilter(new HoraDocumentFilter());
        ((AbstractDocument) FTxtSalida.getDocument()).setDocumentFilter(new HoraDocumentFilter());

        horarioController = new HorarioController();

        cargarDirectiva();
        
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"), "salir");
        getRootPane().getActionMap().put("salir", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Navigation.Volver(FrmConfiguracion.this, new FrmPrincipal(tipoUsuario));
            }
        });

    }

    private FrmConfiguracion() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void cargarDirectiva() {
        String[] datos = horarioController.obtenerDirectiva();

        if (datos[0] != null) {
            FTxtEntrada.setText(datos[0]);
        } else {
            FTxtEntrada.setText("");
        }

        if (datos[1] != null) {
            FTxtSalida.setText(datos[1]);
        } else {
            FTxtSalida.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PnoContenido = new javax.swing.JPanel();
        PnoXd = new javax.swing.JPanel();
        PnoHorario = new javax.swing.JPanel();
        LblTituloHorario = new javax.swing.JLabel();
        FTxtSalida = new javax.swing.JFormattedTextField();
        LblEntrada = new javax.swing.JLabel();
        FTxtEntrada = new javax.swing.JFormattedTextField();
        LblSalida = new javax.swing.JLabel();
        BtnGuardar = new javax.swing.JButton();
        PnoOpciones = new javax.swing.JPanel();
        jbutton2 = new javax.swing.JButton();
        BtnHorario = new javax.swing.JButton();
        LblTitulo = new javax.swing.JLabel();
        BtnVover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnoContenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnoXd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnoHorario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblTituloHorario.setText("configurar horario");
        PnoHorario.add(LblTituloHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 110, 30));
        PnoHorario.add(FTxtSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 100, -1));

        LblEntrada.setText("Entrada");
        PnoHorario.add(LblEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));
        PnoHorario.add(FTxtEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 100, -1));

        LblSalida.setText("Salida");
        PnoHorario.add(LblSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });
        PnoHorario.add(BtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        PnoXd.add(PnoHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 570));

        PnoContenido.add(PnoXd, new org.netbeans.lib.awtextra.AbsoluteConstraints(-9, 0, 450, 480));

        PnoOpciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PnoOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbutton2.setText("xxxxxxx");
        jbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton2ActionPerformed(evt);
            }
        });
        PnoOpciones.add(jbutton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 110, 35));

        BtnHorario.setText("Horario");
        BtnHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHorarioActionPerformed(evt);
            }
        });
        PnoOpciones.add(BtnHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 110, 40));

        LblTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        LblTitulo.setText("Configuracion");
        PnoOpciones.add(LblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        BtnVover.setText("Volver");
        BtnVover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoverActionPerformed(evt);
            }
        });
        PnoOpciones.add(BtnVover, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(PnoOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PnoContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnoContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(PnoOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton2ActionPerformed
        cardLayout.show(PnoContenido, "horario");        // TODO add your handling code here:
    }//GEN-LAST:event_jbutton2ActionPerformed

    private void BtnHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHorarioActionPerformed
        cardLayout.show(PnoContenido, "sonido");
    }//GEN-LAST:event_BtnHorarioActionPerformed

    private void BtnVoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoverActionPerformed
        Navigation.Viajar(FrmConfiguracion.this, new FrmPrincipal(tipoUsuario));        // TODO add your handling code here:
    }//GEN-LAST:event_BtnVoverActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        String horaEntrada = FTxtEntrada.getText().trim();
        String horaSalida = FTxtSalida.getText().trim();

        // Validar entrada
        if (!horaEntrada.isEmpty()
                && !horaEntrada.matches("([01]\\d|2[0-3]):[0-5]\\d")) {

            JOptionPane.showMessageDialog(this,"La hora de entrada no es válida.","Error",JOptionPane.ERROR_MESSAGE);

            return;
        }

        // Validar salida
        if (!horaSalida.isEmpty()
                && !horaSalida.matches("([01]\\d|2[0-3]):[0-5]\\d")) {

            JOptionPane.showMessageDialog( this,"La hora de salida no es válida.","Error",JOptionPane.ERROR_MESSAGE);

            return;
        }

        boolean guardado = horarioController.guardarHorario(horaEntrada,horaSalida);

        if (guardado) {

            JOptionPane.showMessageDialog(this,"Horario guardado correctamente.","Configuración",JOptionPane.INFORMATION_MESSAGE);

        } else {

            JOptionPane.showMessageDialog(this,"No se pudo guardar el horario.","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmConfiguracion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnHorario;
    private javax.swing.JButton BtnVover;
    private javax.swing.JFormattedTextField FTxtEntrada;
    private javax.swing.JFormattedTextField FTxtSalida;
    private javax.swing.JLabel LblEntrada;
    private javax.swing.JLabel LblSalida;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JLabel LblTituloHorario;
    private javax.swing.JPanel PnoContenido;
    private javax.swing.JPanel PnoHorario;
    private javax.swing.JPanel PnoOpciones;
    private javax.swing.JPanel PnoXd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbutton2;
    // End of variables declaration//GEN-END:variables
}
