package Visual;

import Controller.BloqueoController;
import java.awt.Image;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import Helpers.Navigation;
import java.awt.Color;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import Controller.Auth.LoginController;
import Controller.User.Sesion;
import Model.Connect;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jose9
 */
public class FrmLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmLogin.class.getName());

    private static int Intentos = 0;
    private static LocalDateTime horaBloqueo = null;
    Sesion ObjSesion = new Sesion();
    BloqueoController bloqueoCtrl = new BloqueoController();
    Connect con = new Connect();
    LoginController ObjLogin = new LoginController();
    
    public FrmLogin() {
        this.setUndecorated(true);
        initComponents();
        Image icon = new ImageIcon(getClass().getResource("/Assets/TaskBarIcon.png")).getImage();
        setIconImage(icon);
        try {
            java.awt.Taskbar.getTaskbar().setIconImage(icon);
        } catch (Exception e) {
        }
        setSize(565, 461);
        setLocationRelativeTo(null);
        setResizable(false);

        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"), "salir");
        getRootPane().getActionMap().put("salir", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Navigation.Salir(FrmLogin.this);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LblContraseña = new javax.swing.JLabel();
        LblCorreo1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LblLogo = new javax.swing.JLabel();
        TxtCorreo = new javax.swing.JTextField();
        TxtContrasena = new javax.swing.JTextField();
        BtnLogin = new javax.swing.JButton();
        LblInstrucciones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblContraseña.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        LblContraseña.setText("Correo");

        LblCorreo1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        LblCorreo1.setText("Correo");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Logo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblLogo))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(LblLogo)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        BtnLogin.setText("Iniciar Sesion");
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });

        LblInstrucciones.setText("Presione ESC o aqui para salir");
        LblInstrucciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblInstruccionesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblInstruccionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblInstruccionesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblCorreo1)
                            .addComponent(TxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblContraseña)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(BtnLogin))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(LblInstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(LblCorreo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(BtnLogin)
                .addGap(37, 37, 37)
                .addComponent(LblInstrucciones)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
    
       
        // Verificar si el equipo está bloqueado
        if (bloqueoCtrl.verificarBloqueo()) {
            JOptionPane.showMessageDialog(this, "Este equipo está bloqueado temporalmente.\n" +"Intente nuevamente después de 5 minutos.","BLOQUEADO", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String correo = TxtCorreo.getText();
        String clave = TxtContrasena.getText();

        try {
            
            //el resultset valida los datos en la bd y si no hay conexion tira error
            ResultSet resultadoLogin = ObjLogin.ValidarUsuario(correo, clave);

            if (resultadoLogin == null) {
                JOptionPane.showMessageDialog(this, "No hay conexión", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (resultadoLogin.next()) {
                
                //setea los datos obtenidos del resultset en los campos correspondientes en la clase sesion
                ObjSesion.setRut(resultadoLogin.getString("Rut"));
                ObjSesion.setNombreReal(resultadoLogin.getString("Nombre"));
                ObjSesion.setApellidoReal(resultadoLogin.getString("Apellido"));
                ObjSesion.setCorreo(resultadoLogin.getString("Correo"));
                ObjSesion.setTipoUsuario(resultadoLogin.getString("Rol"));
                
                //FrmPrincipal ObjPrincipal = new FrmPrincipal(ObjSesion.getTipoUsuario());
                //ObjPrincipal.setVisible(true);
               
                Intentos = 0;
                dispose();
            } else {
                Intentos++;
                JOptionPane.showMessageDialog(this, "Contraseña o usuario inválido", "ERROR", JOptionPane.ERROR_MESSAGE);

                if (Intentos >= 3) {
                    //activa el bloqueo mediante MAC durante 5 minutos comparando hora y fecha del ban con la actual del equipo
                    bloqueoCtrl.activarBloqueo();
                    JOptionPane.showMessageDialog(this,"Demasiados intentos fallidos.\nEl equipo ha sido bloqueado por 5 minutos.","BLOQUEADO", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnLoginActionPerformed

    private void LblInstruccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblInstruccionesMouseClicked
        Navigation.Salir(FrmLogin.this);
    }//GEN-LAST:event_LblInstruccionesMouseClicked

    private void LblInstruccionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblInstruccionesMouseEntered
        LblInstrucciones.setForeground(Color.red);
    }//GEN-LAST:event_LblInstruccionesMouseEntered

    private void LblInstruccionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblInstruccionesMouseExited
        LblInstrucciones.setForeground(Color.black);
    }//GEN-LAST:event_LblInstruccionesMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogin;
    private javax.swing.JLabel LblContraseña;
    private javax.swing.JLabel LblCorreo1;
    private javax.swing.JLabel LblInstrucciones;
    private javax.swing.JLabel LblLogo;
    private javax.swing.JTextField TxtContrasena;
    private javax.swing.JTextField TxtCorreo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
