package Visual;

import Controller.AsistenciasLog.AsistenciaController;
import Controller.User.Sesion;
import Helpers.Navigation;
import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

public class FrmPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipal.class.getName());

    AsistenciaController asistenciaCtrl = new AsistenciaController();
    //crea un objeto de sesion para poder traer datos del usuario actual
    //en este caso el tipo de usuario
    //IMPORTANTE!!! la IA te dira que esto esta mal y no se ejecutara por que esta fuera del constructor
    //pero se equivoca ademas funciona forma global en el codigo, si llamas al objsesion en cualquier parte puedes traer datos
    Sesion ObjSesion = new Sesion();
    String tipoUsuario = ObjSesion.getTipoUsuario();

public FrmPrincipal(String tipoUsuario) {
        this.setUndecorated(true);
        initComponents();
        setSize(720, 480);
        setPreferredSize(new java.awt.Dimension(480, 720));
        setLocationRelativeTo(null);
        setResizable(false);
        BtnAtrasos.setVisible(tipoUsuario.equals(tipoUsuario));

        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"), "salir");
        getRootPane().getActionMap().put("salir", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Navigation.Volver(FrmPrincipal.this, new FrmLogin());
            }
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblInstrucciones = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BtnEntrada = new javax.swing.JButton();
        BtnSalida = new javax.swing.JButton();
        BtnAtrasos = new javax.swing.JButton();
        BtnConfiguracion = new javax.swing.JButton();
        LblMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblInstrucciones.setForeground(new java.awt.Color(0, 0, 0));
        LblInstrucciones.setText("Presione ESC o aqui para salir");
        LblInstrucciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblInstruccionesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblInstruccionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblInstruccionesMouseExited(evt);
            }
        });
        getContentPane().add(LblInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, -1, -1));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 0, 36)); // NOI18N
        jLabel1.setText("Menu de asistencia ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 350, -1));

        BtnEntrada.setText("Entrada");
        BtnEntrada.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEntradaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 120, 60));

        BtnSalida.setText("Salida");
        BtnSalida.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 120, 60));

        BtnAtrasos.setText("Atrasos");
        BtnAtrasos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnAtrasos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasosActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAtrasos, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 120, 40));

        BtnConfiguracion.setText("Configuracion");
        BtnConfiguracion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfiguracionActionPerformed(evt);
            }
        });
        getContentPane().add(BtnConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 130, 60));

        LblMensaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Menu (1).jpg"))); // NOI18N
        LblMensaje.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                LblMensajeComponentRemoved(evt);
            }
        });
        getContentPane().add(LblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void configurarPorRol(String tipoUsuario) {
        tipoUsuario = tipoUsuario.toLowerCase();

        switch (tipoUsuario) {
            case "1":
                BtnEntrada.setVisible(true);
                BtnSalida.setVisible(true);
                BtnAtrasos.setVisible(true);
                BtnConfiguracion.setVisible(true);
                
            case "0":
                BtnEntrada.setVisible(true);
                BtnSalida.setVisible(true);
                BtnAtrasos.setVisible(false);
                BtnConfiguracion.setVisible(false);
                
            default:
                JOptionPane.showMessageDialog(this, "Tipo de usuario no reconocido");
                System.exit(0);
                break;
        }
    }

    private void BtnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEntradaActionPerformed
        try {
            boolean ok = asistenciaCtrl.marcarEntrada(Sesion.getRut());
            if (ok) {
                LblMensaje.setForeground(new Color(0, 128, 0));
                LblMensaje.setText("Entrada marcada correctamente");
            } else {
                LblMensaje.setForeground(Color.red);
                LblMensaje.setText("Ya registraste tu entrada hoy");
            }
        } catch (Exception e) {
            LblMensaje.setForeground(Color.red);
            LblMensaje.setText("Error: no hay conexión con la base de datos");
        }
    }//GEN-LAST:event_BtnEntradaActionPerformed

    private void BtnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalidaActionPerformed
        try {
            boolean ok = asistenciaCtrl.marcarSalida(Sesion.getRut());
            if (ok) {
                LblMensaje.setForeground(new Color(0, 128, 0));
                LblMensaje.setText("Salida marcada correctamente");
            } else {
                LblMensaje.setForeground(Color.red);
                LblMensaje.setText("Debes marcar entrada primero o ya marcaste salida hoy");
            }
        } catch (Exception e) {
            LblMensaje.setForeground(Color.red);
            LblMensaje.setText("Error: no hay conexión con la base de datos");
        }
    }//GEN-LAST:event_BtnSalidaActionPerformed

    private void BtnAtrasosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasosActionPerformed
        Navigation.Viajar(FrmPrincipal.this, new FrmAtrasos(tipoUsuario));
    }//GEN-LAST:event_BtnAtrasosActionPerformed

    private void LblMensajeComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_LblMensajeComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_LblMensajeComponentRemoved

    private void LblInstruccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblInstruccionesMouseClicked
        Navigation.Volver(FrmPrincipal.this, new FrmLogin());
    }//GEN-LAST:event_LblInstruccionesMouseClicked

    private void LblInstruccionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblInstruccionesMouseEntered
        LblInstrucciones.setForeground(Color.red);
    }//GEN-LAST:event_LblInstruccionesMouseEntered

    private void LblInstruccionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblInstruccionesMouseExited
        LblInstrucciones.setForeground(Color.black);
    }//GEN-LAST:event_LblInstruccionesMouseExited

    private void BtnConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfiguracionActionPerformed
        Navigation.Viajar(FrmPrincipal.this, new FrmConfiguracion(tipoUsuario));
    }//GEN-LAST:event_BtnConfiguracionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPrincipal("1").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtrasos;
    private javax.swing.JButton BtnConfiguracion;
    private javax.swing.JButton BtnEntrada;
    private javax.swing.JButton BtnSalida;
    private javax.swing.JLabel LblInstrucciones;
    private javax.swing.JLabel LblMensaje;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
