package Visual;

import Controller.Asistencias.AsistenciaController;
import Controller.User.Sesion;
import Helpers.Navigation;
import java.awt.Color;
import javax.swing.JOptionPane;

public class FrmPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipal.class.getName());

    AsistenciaController asistenciaCtrl = new AsistenciaController();
    private static final String ROL_ADMIN = "1";

    public FrmPrincipal(String tipoUsuario) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        BtnAtrasos.setVisible(ROL_ADMIN.equals(tipoUsuario));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnEntrada = new javax.swing.JButton();
        BtnSalida = new javax.swing.JButton();
        LblMensaje = new javax.swing.JLabel();
        BtnAtrasos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Menu de asistencia ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 14, 110, -1));

        BtnEntrada.setText("jButton1");
        BtnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEntradaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        BtnSalida.setText("jButton2");
        BtnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        LblMensaje.setText("jLabel2");
        getContentPane().add(LblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        BtnAtrasos.setText("jButton3");
        BtnAtrasos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasosActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAtrasos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEntradaActionPerformed
        try {
            boolean ok = asistenciaCtrl.marcarEntrada(Sesion.getRut());
            if (ok) {
                LblMensaje.setForeground(new Color(0, 128, 0));
                LblMensaje.setText("Entrada marcada correctamente");
            } else {
                LblMensaje.setForeground(Color.red);
                LblMensaje.setText("Ya registraste tu entrada hoy");
            }
        } catch (Exception e) {
            LblMensaje.setForeground(Color.red);
            LblMensaje.setText("Error: no hay conexión con la base de datos");
        }
    }//GEN-LAST:event_BtnEntradaActionPerformed

    private void BtnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalidaActionPerformed
        try {
            boolean ok = asistenciaCtrl.marcarSalida(Sesion.getRut());
            if (ok) {
                LblMensaje.setForeground(new Color(0, 128, 0));
                LblMensaje.setText("Salida marcada correctamente");
            } else {
                LblMensaje.setForeground(Color.red);
                LblMensaje.setText("Debes marcar entrada primero o ya marcaste salida hoy");
            }
        } catch (Exception e) {
            LblMensaje.setForeground(Color.red);
            LblMensaje.setText("Error: no hay conexión con la base de datos");
        }
    }//GEN-LAST:event_BtnSalidaActionPerformed

    private void BtnAtrasosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasosActionPerformed
        FrmAtrasos ObjAtrasos = new FrmAtrasos();
        ObjAtrasos.setVisible(true);
    }//GEN-LAST:event_BtnAtrasosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPrincipal("1").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtrasos;
    private javax.swing.JButton BtnEntrada;
    private javax.swing.JButton BtnSalida;
    private javax.swing.JLabel LblMensaje;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
