/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Visual;

import Helpers.RutHelper;
import Controller.User.CrudUsuarios;
import Controller.User.Sesion;
import Controller.User.Usuario;
import Helpers.Navigation;
import Model.Connect;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import Controller.User.ListarUsuarios;
import Helpers.ClaveGenerator;
import Helpers.CorreoGenerator;

/**
 *
 * @author jose9
 */
public class FrmRegistro extends javax.swing.JFrame {

    Sesion ObjSesion = new Sesion();
    CrudUsuarios UsuariosCrud = new CrudUsuarios();
    ListarUsuarios Users = new ListarUsuarios();
    Usuario u = new Usuario();
    String tipoUsuarioOriginal;
    String tipoUsuario = ObjSesion.getTipoUsuario();

    public FrmRegistro(String tipoUsuario) {
        this.setUndecorated(true);
        initComponents();
        Image icon = new ImageIcon(getClass().getResource("/Assets/TaskBarIcon.png")).getImage();
        setLocationRelativeTo(null);
        setIconImage(icon);
        try {
            java.awt.Taskbar.getTaskbar().setIconImage(icon);
        } catch (Exception e) {
        }
        setSize(965, 498);
        setResizable(false);

        MostrarDatosTabla();

        CorreoGenerator.configurar(TxtNombre, TxtApellido, TxtRut, TxtCorreo);
        ClaveGenerator.configurar(TxtNombre, TxtApellido, TxtRut, TxtClave);

        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"), "salir");
        getRootPane().getActionMap().put("salir", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Navigation.Volver(FrmRegistro.this, new FrmPrincipal(tipoUsuario));
            }
        });

        TxtRut.addActionListener(e -> BtnBuscar.doClick());

        TxtCorreo.setEnabled(false);
        TxtClave.setEnabled(false);

    }

    private FrmRegistro() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        LblNombre = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        LblApellido = new javax.swing.JLabel();
        TxtApellido = new javax.swing.JTextField();
        LblContraseña = new javax.swing.JLabel();
        LblTipoUsuario = new javax.swing.JLabel();
        CmbTipoUsuario = new javax.swing.JComboBox<>();
        LblTotalUsuarios = new javax.swing.JLabel();
        BtnRegistrar = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();
        TxtClave = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblDatos = new javax.swing.JTable();
        LblRut = new javax.swing.JLabel();
        TxtRut = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        BtnRecarga = new javax.swing.JButton();
        TxtCorreo = new javax.swing.JTextField();
        LblCorreo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ChkCustomEmail = new javax.swing.JCheckBox();
        ChkCustomPass = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblTitulo.setText("Registro de Usuarios");
        jPanel1.add(LblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 197, -1));

        LblNombre.setText("Nombre");
        jPanel1.add(LblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 97, -1));

        TxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 160, -1));

        LblApellido.setText("Apellido");
        jPanel1.add(LblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 78, -1));

        TxtApellido.setToolTipText("");
        TxtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(TxtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 160, -1));

        LblContraseña.setText("Contraseña");
        jPanel1.add(LblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 66, -1));

        LblTipoUsuario.setText("Tipo Usuario");
        jPanel1.add(LblTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 101, 20));

        CmbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado", "Administrador" }));
        CmbTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbTipoUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(CmbTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 335, -1));

        LblTotalUsuarios.setText("Total usuarios : ¿?");
        jPanel1.add(LblTotalUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 343, 188, -1));

        BtnRegistrar.setText("Registrar");
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 368, 140, 45));
        BtnRegistrar.getAccessibleContext().setAccessibleName("");

        BtnVolver.setText("Volver");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(BtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 419, 140, 45));
        BtnVolver.getAccessibleContext().setAccessibleName("");

        jPanel1.add(TxtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 331, -1));

        TblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TblDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblDatos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 20, 547, 280));

        LblRut.setText("Rut");
        jPanel1.add(LblRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 20, -1));

        TxtRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRutActionPerformed(evt);
            }
        });
        TxtRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtRutKeyTyped(evt);
            }
        });
        jPanel1.add(TxtRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 253, -1));

        BtnBuscar.setText("Buscar");
        BtnBuscar.setToolTipText("");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 100, -1, -1));

        BtnModificar.setText("Modificar");
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 419, 140, 45));
        BtnModificar.getAccessibleContext().setAccessibleName("");

        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 368, 140, 45));
        BtnEliminar.getAccessibleContext().setAccessibleName("");

        BtnLimpiar.setText("Limpiar campos");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 368, 170, 45));
        BtnLimpiar.getAccessibleContext().setAccessibleName("");

        BtnRecarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/refresh-page-option.png"))); // NOI18N
        BtnRecarga.setText("Recargar datos");
        BtnRecarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRecargaActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRecarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 419, 170, 45));
        BtnRecarga.getAccessibleContext().setAccessibleName("");

        jPanel1.add(TxtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 331, -1));

        LblCorreo.setText("Correo");
        jPanel1.add(LblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ChkCustomEmail.setText("Email Personalizado");
        ChkCustomEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkCustomEmailActionPerformed(evt);
            }
        });
        jPanel2.add(ChkCustomEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        ChkCustomPass.setText("Contraseña personalizada");
        ChkCustomPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkCustomPassActionPerformed(evt);
            }
        });
        jPanel2.add(ChkCustomPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 340, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private String safe(Object valor) {
        return valor == null ? "" : valor.toString();
    }

    public void MostrarDatosTabla() {
        DefaultTableModel ObjModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        ObjModel.addColumn("Rut");
        ObjModel.addColumn("Nombre");
        ObjModel.addColumn("Apellido");
        ObjModel.addColumn("Correo");
        ObjModel.addColumn("Clave");
        ObjModel.addColumn("Rol");

        TblDatos.setModel(ObjModel);

        ResultSet resultado = null;
        Connection con = null;
        try {
            resultado = Users.ListarTodos();
            if (resultado != null) {
                con = resultado.getStatement().getConnection();

            }

            int cantRegistros = 0;
            while (resultado != null && resultado.next()) {
                ObjModel.addRow(new Object[]{
                    resultado.getString("Rut"),
                    resultado.getString("Nombre"),
                    resultado.getString("Apellido"),
                    resultado.getString("Correo"),
                    resultado.getString("Contrasena"),
                    resultado.getString("Rol"),});

                cantRegistros++;

            }

            LblTotalUsuarios.setText("Total usuarios: " + cantRegistros);

        } catch (SQLException e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "No se pudieron cargar los datos", "Alerta", JOptionPane.WARNING_MESSAGE);
        }

    }

    private void TxtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtApellidoActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed

        dispose();
        FrmPrincipal ObjPrincipal = new FrmPrincipal(ObjSesion.getTipoUsuario());
        ObjPrincipal.setVisible(true);
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed
        String Rut = TxtRut.getText();
        //String dv = TxtVerificador.getText();
        String Nombre = TxtNombre.getText();
        String Apellido = TxtApellido.getText().trim();
        String Correo = TxtCorreo.getText().trim();
        String Clave = TxtClave.getText();

        String TipoUsuario = (String) CmbTipoUsuario.getSelectedItem();

        if (TipoUsuario.equals("Empleado")) {
            TipoUsuario = "0";
        } else {
            TipoUsuario = "1";
        }

        if (Rut.isEmpty() || Nombre.isEmpty() || Apellido.isEmpty() || Clave.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Faltan campos por completar", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        u.setRut(Rut);
        u.setNombre(Nombre);
        u.setApellido(Apellido);
        u.setCorreo(Correo);
        u.setClave(Clave);
        u.setTipoUsuario(TipoUsuario);

        UsuariosCrud.grabar(u);
        MostrarDatosTabla();
    }//GEN-LAST:event_BtnRegistrarActionPerformed

    private void CmbTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbTipoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbTipoUsuarioActionPerformed

    private void TblDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblDatosMouseClicked
        int filaSeleccionada = TblDatos.rowAtPoint(evt.getPoint());

        TxtRut.setText(safe(TblDatos.getValueAt(filaSeleccionada, 0)));
        TxtNombre.setText(safe(TblDatos.getValueAt(filaSeleccionada, 1)));
        TxtApellido.setText(safe(TblDatos.getValueAt(filaSeleccionada, 2)));
        TxtCorreo.setText(safe(TblDatos.getValueAt(filaSeleccionada, 3)));
        TxtClave.setText(safe(TblDatos.getValueAt(filaSeleccionada, 4)));
        String Us = safe(TblDatos.getValueAt(filaSeleccionada, 5));

        if (Us.equals("0")) {
            CmbTipoUsuario.setSelectedItem("Empleado");
        } else {
            CmbTipoUsuario.setSelectedItem("Administrador");
        }

        RutHelper.validarYColorearRut(TxtRut);

    }//GEN-LAST:event_TblDatosMouseClicked

    private void TxtRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRutActionPerformed

    private void TxtRutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtRutKeyTyped
        RutHelper.manejarRut(TxtRut, evt);
    }//GEN-LAST:event_TxtRutKeyTyped

    //modificar campos para buscar
    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        String Rut = TxtRut.getText();
        if (Rut.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingresa un rut para buscar", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            Usuario u = UsuariosCrud.buscar(Rut);
            if (u != null) {
                TxtRut.setText(u.getRut());
                TxtNombre.setText(u.getNombre());
                TxtApellido.setText(u.getApellido());
                TxtClave.setText(u.getClave());
                CmbTipoUsuario.setSelectedItem(u.getTipoUsuario());

            } else {
                JOptionPane.showMessageDialog(null, "Empleado no encontrado", "Advertencia", JOptionPane.WARNING_MESSAGE);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Faltan campos por completar", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        String rut = TxtRut.getText();
        if (rut.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingresa un rut", "Alert", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String tipoUsuario;

        String nombre = TxtNombre.getText();
        String usuario = TxtApellido.getText();
        String clave = TxtClave.getText();

        if (tipoUsuarioOriginal.equalsIgnoreCase("1")) {
            tipoUsuario = "1";
        } else {
            tipoUsuario = (String) CmbTipoUsuario.getSelectedItem();

            if (tipoUsuario.equals("Empleado")) {
                tipoUsuario = "0";
            } else {
                tipoUsuario = "1";
            }
        }

        u.setRut(rut);
        u.setNombre(nombre);
        u.setApellido(usuario);
        u.setClave(clave);
        u.setTipoUsuario(tipoUsuario);

        UsuariosCrud.actualizar(u);

        MostrarDatosTabla();

    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        String Rut = TxtRut.getText();
        if (Rut.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingresa un rut para eliminar", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int Confirm = JOptionPane.showConfirmDialog(this, "Estas seguro de eliminar a este Empleado?", "Confirmacion", JOptionPane.YES_NO_OPTION);

        if (Confirm == JOptionPane.YES_OPTION) {
            UsuariosCrud.eiliminar(Rut);

        }
        MostrarDatosTabla();
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        TxtRut.setText(null);
        TxtApellido.setText(null);
        TxtCorreo.setText(null);
        TxtClave.setText(null);
        TxtNombre.setText(null);
        CmbTipoUsuario.setSelectedIndex(0);
        ChkCustomEmail.setSelected(false);
        ChkCustomPass.setSelected(false);

    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void BtnRecargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRecargaActionPerformed
        MostrarDatosTabla();
    }//GEN-LAST:event_BtnRecargaActionPerformed

    private void TxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreActionPerformed

    private void ChkCustomEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkCustomEmailActionPerformed
        if (ChkCustomEmail.isSelected()) {
            TxtCorreo.setEnabled(true);
        } else {
            TxtCorreo.setEnabled(false);
        }
    }//GEN-LAST:event_ChkCustomEmailActionPerformed

    private void ChkCustomPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkCustomPassActionPerformed
        if (ChkCustomPass.isSelected()) {
            TxtClave.setEnabled(true);
        } else {
            TxtClave.setEnabled(false);
        }
    }//GEN-LAST:event_ChkCustomPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton BtnRecarga;
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JCheckBox ChkCustomEmail;
    private javax.swing.JCheckBox ChkCustomPass;
    private javax.swing.JComboBox<String> CmbTipoUsuario;
    private javax.swing.JLabel LblApellido;
    private javax.swing.JLabel LblContraseña;
    private javax.swing.JLabel LblCorreo;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JLabel LblRut;
    private javax.swing.JLabel LblTipoUsuario;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JLabel LblTotalUsuarios;
    private javax.swing.JTable TblDatos;
    private javax.swing.JTextField TxtApellido;
    private javax.swing.JTextField TxtClave;
    private javax.swing.JTextField TxtCorreo;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtRut;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
